language: php

matrix:
  include:
    - env: DB=mysql; MW=REL1_28; TYPE=coverage
      php: 7.0
    - env: DB=sqlite; MW=1.26.4
      php: 5.3
      dist: precise
      sudo: required
    - env: DB=mysql; MW=master;
      php: 5.6
  allow_failures:
    - env: DB=mysql; MW=master;

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-glossary.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
